version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - PROMETHEUS_PORT=9091
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    depends_on:
      - redis
      - prometheus
      - grafana
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"  # Changed external port to 6380
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"  # Changed external port to 9091
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  redis_data:
  prometheus_data:
  grafana_data:
