# Generated by Django 4.2.7 on 2025-03-24 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.IntegerField()),
                ('interaction_type', models.CharField(max_length=50)),
                ('session_key', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_spent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('entry_page', models.CharField(max_length=255)),
                ('exit_page', models.CharField(max_length=255, null=True)),
                ('pages_viewed', models.JSONField(default=list)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('conversion_achieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pageview',
            name='browser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='device_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='is_bounce',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='os',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referrer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='clicked_results',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='successful_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='content_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='exit_intent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='form_interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['device_type'], name='analytics_p_device__a59989_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['country'], name='analytics_p_country_59a416_idx'),
        ),
        migrations.AddIndex(
            model_name='userflow',
            index=models.Index(fields=['session_key'], name='analytics_u_session_c0b3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='userflow',
            index=models.Index(fields=['start_time'], name='analytics_u_start_t_a0a697_idx'),
        ),
        migrations.AddField(
            model_name='contentinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentinteraction',
            index=models.Index(fields=['content_type', 'content_id'], name='analytics_c_content_fad2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='contentinteraction',
            index=models.Index(fields=['timestamp'], name='analytics_c_timesta_aeb267_idx'),
        ),
    ]
